// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: messageWithSignature.proto

package messageSigpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgType int32

const (
	MsgType_Raw                    MsgType = 0
	MsgType_Ack                    MsgType = 1
	MsgType_Wit                    MsgType = 2
	MsgType_Catchup                MsgType = 3
	MsgType_BlsSetupPhase          MsgType = 4
	MsgType_BlsMembershipKeysParts MsgType = 5
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0: "Raw",
		1: "Ack",
		2: "Wit",
		3: "Catchup",
		4: "BlsSetupPhase",
		5: "BlsMembershipKeysParts",
	}
	MsgType_value = map[string]int32{
		"Raw":                    0,
		"Ack":                    1,
		"Wit":                    2,
		"Catchup":                3,
		"BlsSetupPhase":          4,
		"BlsMembershipKeysParts": 5,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_messageWithSignature_proto_enumTypes[0].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_messageWithSignature_proto_enumTypes[0]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *MsgType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = MsgType(num)
	return nil
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_messageWithSignature_proto_rawDescGZIP(), []int{0}
}

type PbMessageSig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgType            *MsgType        `protobuf:"varint,1,req,name=Msg_type,json=MsgType,enum=messageSigpb.MsgType" json:"Msg_type,omitempty"`
	Source             *int64          `protobuf:"varint,2,req,name=source" json:"source,omitempty"`
	Step               *int64          `protobuf:"varint,3,req,name=step" json:"step,omitempty"`
	History            []*PbMessageSig `protobuf:"bytes,4,rep,name=history" json:"history,omitempty"`
	Signature          []byte          `protobuf:"bytes,5,opt,name=signature" json:"signature,omitempty"`
	Mask               []byte          `protobuf:"bytes,6,opt,name=mask" json:"mask,omitempty"`
	PublicKey          []byte          `protobuf:"bytes,7,opt,name=public_key,json=publicKey" json:"public_key,omitempty"`
	PartMembershipKeys [][]byte        `protobuf:"bytes,8,rep,name=part_membership_keys,json=partMembershipKeys" json:"part_membership_keys,omitempty"`
}

func (x *PbMessageSig) Reset() {
	*x = PbMessageSig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messageWithSignature_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PbMessageSig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbMessageSig) ProtoMessage() {}

func (x *PbMessageSig) ProtoReflect() protoreflect.Message {
	mi := &file_messageWithSignature_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbMessageSig.ProtoReflect.Descriptor instead.
func (*PbMessageSig) Descriptor() ([]byte, []int) {
	return file_messageWithSignature_proto_rawDescGZIP(), []int{0}
}

func (x *PbMessageSig) GetMsgType() MsgType {
	if x != nil && x.MsgType != nil {
		return *x.MsgType
	}
	return MsgType_Raw
}

func (x *PbMessageSig) GetSource() int64 {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return 0
}

func (x *PbMessageSig) GetStep() int64 {
	if x != nil && x.Step != nil {
		return *x.Step
	}
	return 0
}

func (x *PbMessageSig) GetHistory() []*PbMessageSig {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *PbMessageSig) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *PbMessageSig) GetMask() []byte {
	if x != nil {
		return x.Mask
	}
	return nil
}

func (x *PbMessageSig) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *PbMessageSig) GetPartMembershipKeys() [][]byte {
	if x != nil {
		return x.PartMembershipKeys
	}
	return nil
}

var File_messageWithSignature_proto protoreflect.FileDescriptor

var file_messageWithSignature_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x57, 0x69, 0x74, 0x68, 0x53, 0x69, 0x67,
	0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x69, 0x67, 0x70, 0x62, 0x22, 0xa6, 0x02, 0x0a, 0x0c, 0x50,
	0x62, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x69, 0x67, 0x12, 0x31, 0x0a, 0x08, 0x4d,
	0x73, 0x67, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0e, 0x32, 0x16, 0x2e,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x69, 0x67, 0x70, 0x62, 0x2e, 0x4d, 0x73, 0x67,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x52, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x03, 0x52, 0x06,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x74, 0x65, 0x70, 0x18, 0x03,
	0x20, 0x02, 0x28, 0x03, 0x52, 0x04, 0x73, 0x74, 0x65, 0x70, 0x12, 0x34, 0x0a, 0x07, 0x68, 0x69,
	0x73, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x69, 0x67, 0x70, 0x62, 0x2e, 0x50, 0x62, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x53, 0x69, 0x67, 0x52, 0x07, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79,
	0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6d, 0x61, 0x73, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x6d, 0x61,
	0x73, 0x6b, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65,
	0x79, 0x12, 0x30, 0x0a, 0x14, 0x70, 0x61, 0x72, 0x74, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x73, 0x68, 0x69, 0x70, 0x5f, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0c, 0x52,
	0x12, 0x70, 0x61, 0x72, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x4b,
	0x65, 0x79, 0x73, 0x2a, 0x61, 0x0a, 0x08, 0x4d, 0x73, 0x67, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x07, 0x0a, 0x03, 0x52, 0x61, 0x77, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x63, 0x6b, 0x10,
	0x01, 0x12, 0x07, 0x0a, 0x03, 0x57, 0x69, 0x74, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x61,
	0x74, 0x63, 0x68, 0x75, 0x70, 0x10, 0x03, 0x12, 0x11, 0x0a, 0x0d, 0x42, 0x6c, 0x73, 0x53, 0x65,
	0x74, 0x75, 0x70, 0x50, 0x68, 0x61, 0x73, 0x65, 0x10, 0x04, 0x12, 0x1a, 0x0a, 0x16, 0x42, 0x6c,
	0x73, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x4b, 0x65, 0x79, 0x73, 0x50,
	0x61, 0x72, 0x74, 0x73, 0x10, 0x05,
}

var (
	file_messageWithSignature_proto_rawDescOnce sync.Once
	file_messageWithSignature_proto_rawDescData = file_messageWithSignature_proto_rawDesc
)

func file_messageWithSignature_proto_rawDescGZIP() []byte {
	file_messageWithSignature_proto_rawDescOnce.Do(func() {
		file_messageWithSignature_proto_rawDescData = protoimpl.X.CompressGZIP(file_messageWithSignature_proto_rawDescData)
	})
	return file_messageWithSignature_proto_rawDescData
}

var file_messageWithSignature_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_messageWithSignature_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_messageWithSignature_proto_goTypes = []interface{}{
	(MsgType)(0),         // 0: messageSigpb.Msg_type
	(*PbMessageSig)(nil), // 1: messageSigpb.PbMessageSig
}
var file_messageWithSignature_proto_depIdxs = []int32{
	0, // 0: messageSigpb.PbMessageSig.Msg_type:type_name -> messageSigpb.Msg_type
	1, // 1: messageSigpb.PbMessageSig.history:type_name -> messageSigpb.PbMessageSig
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_messageWithSignature_proto_init() }
func file_messageWithSignature_proto_init() {
	if File_messageWithSignature_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_messageWithSignature_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PbMessageSig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_messageWithSignature_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messageWithSignature_proto_goTypes,
		DependencyIndexes: file_messageWithSignature_proto_depIdxs,
		EnumInfos:         file_messageWithSignature_proto_enumTypes,
		MessageInfos:      file_messageWithSignature_proto_msgTypes,
	}.Build()
	File_messageWithSignature_proto = out.File
	file_messageWithSignature_proto_rawDesc = nil
	file_messageWithSignature_proto_goTypes = nil
	file_messageWithSignature_proto_depIdxs = nil
}
