version: '3.6'

services:
# bootstrap nodes
  bsn1:
    command: [ "./bsn"]
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: p2p-bridge_img
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # https://github.com/docker/compose/issues/3584
      - ./.data/keys/bsn1:/go/keys
    env_file:
      - .env.sentry
    networks:
      static-network:
        ipv4_address: 172.20.64.11

  bsn2:
    command: [ "./bsn" ]
    image: p2p-bridge_img
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # https://github.com/docker/compose/issues/3584
      - ./.data/keys/bsn2:/go/keys
    env_file:
      - .env.sentry
    networks:
      static-network:
        ipv4_address: 172.20.64.12

  bsn3:
    command: [ "./bsn"]
    image: p2p-bridge_img
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # https://github.com/docker/compose/issues/3584
      - ./.data/keys/bsn3:/go/keys
    env_file:
      - .env.sentry
    networks:
      static-network:
        ipv4_address: 172.20.64.13

  # protocol nodes
  node1:
    command: [ "./bridge", "-cnf", "bridge.yaml" ]
    image: p2p-bridge_img
    restart: always
    depends_on:
      - bsn1
      - bsn2
      - bsn3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # https://github.com/docker/compose/issues/3584
      - .data/bridge.yaml:/go/bridge.yaml
      - .data/keys/node1:/go/keys
    env_file:
      - .env.sentry
      - .env.prom
    networks:
      static-network:
        ipv4_address: 172.20.32.11

  node2:
    command: [ "./bridge", "-cnf", "bridge.yaml" ]
    image: p2p-bridge_img
    restart: always
    depends_on:
      - bsn1
      - bsn2
      - bsn3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # https://github.com/docker/compose/issues/3584
      - .data/bridge.yaml:/go/bridge.yaml
      - .data/keys/node2:/go/keys
    env_file:
      - .env.sentry
      - .env.prom
    networks:
      static-network:
        ipv4_address: 172.20.32.12

  node3:
    command: [ "./bridge", "-cnf", "bridge.yaml" ]
    image: p2p-bridge_img
    restart: always
    depends_on:
      - bsn1
      - bsn2
      - bsn3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # https://github.com/docker/compose/issues/3584
      - .data/bridge.yaml:/go/bridge.yaml
      - .data/keys/node3:/go/keys
    env_file:
      - .env.sentry
      - .env.prom
    networks:
      static-network:
        ipv4_address: 172.20.32.13

  node4:
    command: [ "./bridge", "-cnf", "bridge.yaml" ]
    image: p2p-bridge_img
    restart: always
    depends_on:
      - bsn1
      - bsn2
      - bsn3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # https://github.com/docker/compose/issues/3584
      - .data/bridge.yaml:/go/bridge.yaml
      - .data/keys/node4:/go/keys
    env_file:
      - .env.sentry
      - .env.prom
    networks:
      static-network:
        ipv4_address: 172.20.32.14

  node5:
    command: [ "./bridge", "-cnf", "bridge.yaml" ]
    image: p2p-bridge_img
    restart: always
    depends_on:
      - bsn1
      - bsn2
      - bsn3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # https://github.com/docker/compose/issues/3584
      - .data/bridge.yaml:/go/bridge.yaml
      - .data/keys/node5:/go/keys
    env_file:
      - .env.sentry
      - .env.prom
    networks:
      static-network:
        ipv4_address: 172.20.32.15

  node6:
    command: [ "./bridge", "-cnf", "bridge.yaml" ]
    image: p2p-bridge_img
    restart: always
    depends_on:
      - bsn1
      - bsn2
      - bsn3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # https://github.com/docker/compose/issues/3584
      - .data/bridge.yaml:/go/bridge.yaml
      - .data/keys/node6:/go/keys
    env_file:
      - .env.sentry
      - .env.prom
    networks:
      static-network:
        ipv4_address: 172.20.32.16

  node7:
    command: [ "./bridge", "-cnf", "bridge.yaml" ]
    image: p2p-bridge_img
    restart: always
    depends_on:
      - bsn1
      - bsn2
      - bsn3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # https://github.com/docker/compose/issues/3584
      - .data/bridge.yaml:/go/bridge.yaml
      - .data/keys/node7:/go/keys
    env_file:
      - .env.sentry
      - .env.prom
    networks:
      static-network:
        ipv4_address: 172.20.32.17

  prometheus:
    image: prom/prometheus
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./.data/prometheus.yaml:/etc/prometheus/prometheus.yml
    networks:
      - static-network
    depends_on:
      - node1
      - node2
      - node3
      - node4
      - node5
      - node6
      - node7

networks:
  static-network:
    name: dev_net_1
    ipam:
      config:
        - subnet: 172.20.0.0/16
