version: '3.6'

services:
  # bootstrap nodes
  bsn1:
    command: [ "./bsn"]
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: p2p-bridge_img
    env_file:
      - .env.sentry
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # https://github.com/docker/compose/issues/3584
      - ./.data/keys/bsn1:/go/keys
    networks:
      static-network:
        ipv4_address: 172.20.64.11

  bsn2:
    command: [ "./bsn" ]
    image: p2p-bridge_img
    env_file:
      - .env.sentry
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # https://github.com/docker/compose/issues/3584
      - ./.data/keys/bsn2:/go/keys
    networks:
      static-network:
        ipv4_address: 172.20.64.12

  bsn3:
    command: [ "./bsn"]
    image: p2p-bridge_img
    env_file:
      - .env.sentry
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # https://github.com/docker/compose/issues/3584
      - ./.data/keys/bsn3:/go/keys
    networks:
      static-network:
        ipv4_address: 172.20.64.13

  # protocol nodes
  node1:
    command: [ "./bridge", "-cnf", "bridge.yaml" ]
    image: p2p-bridge_img
    depends_on:
      - ganache_net1
      - ganache_net2
      - ganache_net3
      - bsn1
      - bsn2
      - bsn3
    env_file:
      - .env.sentry
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # https://github.com/docker/compose/issues/3584
      - .data/bridge.yaml:/go/bridge.yaml
      - .data/keys/node1:/go/keys
    networks:
      static-network:
        ipv4_address: 172.20.32.11

  node2:
    command: [ "./bridge", "-cnf", "bridge.yaml" ]
    image: p2p-bridge_img
    depends_on:
      - ganache_net1
      - ganache_net2
      - ganache_net3
      - bsn1
      - bsn2
      - bsn3
    env_file:
      - .env.sentry
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # https://github.com/docker/compose/issues/3584
      - .data/bridge.yaml:/go/bridge.yaml
      - .data/keys/node2:/go/keys
    networks:
      static-network:
        ipv4_address: 172.20.32.12

  node3:
    command: [ "./bridge", "-cnf", "bridge.yaml" ]
    image: p2p-bridge_img
    depends_on:
      - ganache_net1
      - ganache_net2
      - ganache_net3
      - bsn1
      - bsn2
      - bsn3
    env_file:
      - .env.sentry
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # https://github.com/docker/compose/issues/3584
      - .data/bridge.yaml:/go/bridge.yaml
      - .data/keys/node3:/go/keys
    networks:
      static-network:
        ipv4_address: 172.20.32.13

  node4:
    command: [ "./bridge", "-cnf", "bridge.yaml" ]
    image: p2p-bridge_img
    depends_on:
      - ganache_net1
      - ganache_net2
      - ganache_net3
      - bsn1
      - bsn2
      - bsn3
    env_file:
      - .env.sentry
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # https://github.com/docker/compose/issues/3584
      - .data/bridge.yaml:/go/bridge.yaml
      - .data/keys/node4:/go/keys
    networks:
      static-network:
        ipv4_address: 172.20.32.14

  node5:
    command: [ "./bridge", "-cnf", "bridge.yaml" ]
    image: p2p-bridge_img
    depends_on:
      - ganache_net1
      - ganache_net2
      - ganache_net3
      - bsn1
      - bsn2
      - bsn3
    env_file:
      - .env.sentry
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # https://github.com/docker/compose/issues/3584
      - .data/bridge.yaml:/go/bridge.yaml
      - .data/keys/node5:/go/keys
    networks:
      static-network:
        ipv4_address: 172.20.32.15

  node6:
    command: [ "./bridge", "-cnf", "bridge.yaml" ]
    image: p2p-bridge_img
    depends_on:
      - ganache_net1
      - ganache_net2
      - ganache_net3
      - bsn1
      - bsn2
      - bsn3
    env_file:
      - .env.sentry
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # https://github.com/docker/compose/issues/3584
      - .data/bridge.yaml:/go/bridge.yaml
      - .data/keys/node6:/go/keys
    networks:
      static-network:
        ipv4_address: 172.20.32.16

  node7:
    command: [ "./bridge", "-cnf", "bridge.yaml" ]
    image: p2p-bridge_img
    depends_on:
      - ganache_net1
      - ganache_net2
      - ganache_net3
      - bsn1
      - bsn2
      - bsn3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # https://github.com/docker/compose/issues/3584
      - .data/bridge.yaml:/go/bridge.yaml
      - .data/keys/node7:/go/keys
    networks:
      static-network:
        ipv4_address: 172.20.32.17

  # dev-adapter:
  #   build:
  #     context: ../
  #     dockerfile: ./p2p-bridge/dev.Dockerfile
  #   depends_on:
  #     - ganache_net1
  #     - ganache_net2
  #   environment:
  #     - TYPE_ADAPTER_ENV=${TYPE_ADAPTER_ENV}
  #     - ECDSA_KEY_1=0x60cc6f7a3b09e5080dc86cc0fd80e29545683ad4336012b221998b448d2d57bb,0x187994e6d93bb29e386fe7ab50232a6a2bea5d6f61046b803b9e9b8306b7d268,0xf5e350eb75d845a8cd538e06331ee6eeb159c54710c6c84c725cd77e2e0dde59,0x9894defbe159c1abba7db3f88b122bf94c6838a28a98af9466e85c8f573c43bc,0xafd8124dd3abec91d07dca54878cd296666a96decd122cc7646e9357df21a6de,0xb433482fbde7e7a9f6fb0d63d60782820dfe8e1f2e58ac9c0281c817d13b64ec,0xa76afd42e10c31cc170f32489a9f6af28efe2b1e6aede2813c3ec7d2907a05e9,0x7eb8b227320968eefa7291cfb5ff81226301b8fb40dc2eace533ec594ddb79e1,0x594e53edfffd4854087d036a8b5a768904be914855ea7985ad094da2f59ce17a,0xa5f9ca32c5fcaf7625a7207261ef274697a2b6ec419050b7165546b99288bc07,0x6926955d28a178b084a54cebd19e7d0107fe02cd9fd5d4f37d430909d90b0259,0x69dbe83e3d9fd2ccef9f10c6cde17b7389e14b68d2b0c6d49dc5a0632ca011ce,0x39f19403a5fb8da5a2afdaad4ed4fe15871d9691e3e8efebdbb715d31736535b,0x611065277d9fac2ebe688d0797e07bc01bd1d0121f630b1ddf7bd5f356d4416e,0xad653f2e32184fe2f5e79c8c745cbca0be4205e3bb48242c75542210a29b7fcb
  #     - ECDSA_KEY_2=0x72a21bf9881eff3ab6e4bd245074cdbb6631388e22318bd4f5df2752b69222cc,0x3fdb56439eb7c05074586993925c6e06103a5b770b46aa29e399cc693d44ddf7,0xe84538a8b4059da88d5a76544329093da99603fe05b0f1332f737c74253688c3,0x469e5c05e289274dd8570c31f2f0f21236f2e071613ac9c565821985e7ae641e,0x95472b385de2c871fb293f07e76a56e8e93ea4e743fe940afbd44c30730211dc,0xd37fe8ab9b9a4f0473c2c7e32b6b218cc398837ce29a548066d52245c345df1a,0xdd9a03e0e395072e4f8b96952264a3cb30efa28bf98342e197d2af8a3d6fc541,0xf8d3535d747014e91637e8b9dcb88f265d13b6219c2c2a93df94659303c42d64,0xef0b0807515081cb8a5c171a1944bc07c1dd27d2184590ac150a7713d335f47a,0x01b039c047c67e23305400d0fec71a79aa0130a8f15dc4d4698281bf6612df2f,0x13e8318ea3359711e7106712f556ec99be0fff058f5017197f3fb5dbadae1f16,0xcc90be77110f973d3a2ccc99b4657e1976e1d3eeb0472a774dc8b6eb981ebb2e,0x07f386df7ea062283e5fa37f52da002aa5eff5a214ba60a1365cbad4694e0843,0x60a82fb2c0ef40d68c81b522b3a74f5ccb742aaf076c8a99b1b1f1d941ce937c,0x63fafc92fd796cbc92fb4d0ba0fdd8db4ae832d74b30c743487df5f95fc793ce
  #     - NETWORK_RPC_1=${NETWORK_RPC_1}
  #     - NETWORK_RPC_2=${NETWORK_RPC_2}
  #   volumes:
  #     - ./:/p2p-bridge
  #     - ../eth-contracts/wrappers:/eth-contracts/wrappers
  #   networks:
  #     static-network:
  #       ipv4_address: 172.20.0.12

  ganache_net1:
    build:
      context: ./
      dockerfile: ./external/eth-contracts/hardhat/docker/network1/ganache/Dockerfile
    volumes:
      - ./.data/chaindata_ganache_net1:/chaindata
    networks:
      static-network:
        ipv4_address: 172.20.128.11
    ports:
      - "172.20.128.11:7545:7545"

  ganache_net2:
    build:
      context: ./
      dockerfile: ./external/eth-contracts/hardhat/docker/network2/ganache/Dockerfile
    volumes:
      - ./.data/chaindata_ganache_net2:/chaindata
    networks:
      static-network:
        ipv4_address: 172.20.128.12
    ports:
      - "172.20.128.12:8545:8545"

  ganache_net3:
    build:
      context: ./
      dockerfile: ./external/eth-contracts/hardhat/docker/network3/ganache/Dockerfile
    volumes:
      - ./.data/chaindata_ganache_net3:/chaindata
    networks:
      static-network:
        ipv4_address: 172.20.128.13
    ports:
      - "172.20.128.13:9545:9545"

networks:
  static-network:
    name: dev_net_1
    ipam:
      config:
        - subnet: 172.20.0.0/16
