version: '3.6'

services:

  node1:
    build:
      context: ../
      dockerfile: ./p2p-bridge/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # https://github.com/docker/compose/issues/3584
    environment:
        - MODE=${MODE}
        - PORT=0
        - TYPE_ADAPTER_ENV=bootstrap.env
        - ECDSA_KEY_1=${ECDSA_KEY_1}
        - ECDSA_KEY_2=${ECDSA_KEY_2}
        - ECDSA_KEY_3=${ECDSA_KEY_3}
        - NETWORK_RPC_1=${NETWORK_RPC_1}
        - NETWORK_RPC_2=${NETWORK_RPC_2}
        - RANDEVOUE=${RANDEVOUE}
    networks:
      static-network:
        ipv4_address: 172.20.128.51

  node2:
    build:
      context: ../
      dockerfile: ./p2p-bridge/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # https://github.com/docker/compose/issues/3584
    environment:
      - MODE=${MODE}
      - PORT=0
      - TYPE_ADAPTER_ENV=bootstrap.env
      - ECDSA_KEY_1=${ECDSA_KEY_1}
      - ECDSA_KEY_2=${ECDSA_KEY_2}
      - ECDSA_KEY_3=${ECDSA_KEY_3}
      - NETWORK_RPC_1=${NETWORK_RPC_1}
      - NETWORK_RPC_2=${NETWORK_RPC_2}
      - RANDEVOUE=${RANDEVOUE}
    networks:
      static-network:
        ipv4_address: 172.20.128.52

  node3:
    build:
      context: ../
      dockerfile: ./p2p-bridge/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # https://github.com/docker/compose/issues/3584
    environment:
      - MODE=${MODE}
      - PORT=0
      - TYPE_ADAPTER_ENV=bootstrap.env
      - ECDSA_KEY_1=${ECDSA_KEY_1}
      - ECDSA_KEY_2=${ECDSA_KEY_2}
      - ECDSA_KEY_3=${ECDSA_KEY_3}
      - NETWORK_RPC_1=${NETWORK_RPC_1}
      - NETWORK_RPC_2=${NETWORK_RPC_2}
      - RANDEVOUE=${RANDEVOUE}
    networks:
      static-network:
        ipv4_address: 172.20.128.53


  node4:
    build:
      context: ../
      dockerfile: ./p2p-bridge/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # https://github.com/docker/compose/issues/3584
    environment:
      - MODE=${MODE}
      - PORT=0
      - TYPE_ADAPTER_ENV=bootstrap.env
      - ECDSA_KEY_1=${ECDSA_KEY_1}
      - ECDSA_KEY_2=${ECDSA_KEY_2}
      - ECDSA_KEY_3=${ECDSA_KEY_3}
      - NETWORK_RPC_1=${NETWORK_RPC_1}
      - NETWORK_RPC_2=${NETWORK_RPC_2}
      - RANDEVOUE=${RANDEVOUE}
    networks:
      static-network:
        ipv4_address: 172.20.128.54


  node5:
    build:
      context: ../
      dockerfile: ./p2p-bridge/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # https://github.com/docker/compose/issues/3584
    environment:
      - MODE=${MODE}
      - PORT=0
      - TYPE_ADAPTER_ENV=bootstrap.env
      - ECDSA_KEY_1=${ECDSA_KEY_1}
      - ECDSA_KEY_2=${ECDSA_KEY_2}
      - ECDSA_KEY_3=${ECDSA_KEY_3}
      - NETWORK_RPC_1=${NETWORK_RPC_1}
      - NETWORK_RPC_2=${NETWORK_RPC_2}
      - RANDEVOUE=${RANDEVOUE}
    networks:
      static-network:
        ipv4_address: 172.20.128.55

  node6:
    build:
      context: ../
      dockerfile: ./p2p-bridge/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # https://github.com/docker/compose/issues/3584
    environment:
      - MODE=${MODE}
      - PORT=0
      - TYPE_ADAPTER_ENV=bootstrap.env
      - ECDSA_KEY_1=${ECDSA_KEY_1}
      - ECDSA_KEY_2=${ECDSA_KEY_2}
      - ECDSA_KEY_3=${ECDSA_KEY_3}
      - NETWORK_RPC_1=${NETWORK_RPC_1}
      - NETWORK_RPC_2=${NETWORK_RPC_2}
      - RANDEVOUE=${RANDEVOUE}
    networks:
      static-network:
        ipv4_address: 172.20.128.56


  node7:
    build:
      context: ../
      dockerfile: ./p2p-bridge/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # https://github.com/docker/compose/issues/3584
    environment:
      - MODE=${MODE}
      - PORT=0
      - TYPE_ADAPTER_ENV=bootstrap.env
      - ECDSA_KEY_1=${ECDSA_KEY_1}
      - ECDSA_KEY_2=${ECDSA_KEY_2}
      - ECDSA_KEY_3=${ECDSA_KEY_3}
      - NETWORK_RPC_1=${NETWORK_RPC_1}
      - NETWORK_RPC_2=${NETWORK_RPC_2}
      - RANDEVOUE=${RANDEVOUE}
    networks:
      static-network:
        ipv4_address: 172.20.128.57


networks:
  static-network:
    name: dev_net_1
    ipam:
      config:
        - subnet: 172.20.0.0/16
