version: '3.6'

services:

  bootstrap_node:
    build:
      context: ../
      dockerfile: ./p2p-bridge/Dockerfile
    depends_on:
      - ganache_net1
      - ganache_net2
    environment:
        - TYPE_ADAPTER_ENV=./bootstrap.env
    networks:
      static-network:
        ipv4_address: 173.20.128.55
  dev-adapter:
    build:
      context: ../
      dockerfile: ./p2p-bridge/dev.Dockerfile
    depends_on:
      - ganache_net1
      - ganache_net2
    environment:
      - TYPE_ADAPTER_ENV=${TYPE_ADAPTER_ENV}
    volumes:
      - ./:/p2p-bridge      
      - ../eth-contracts/wrappers:/eth-contracts/wrappers
    networks:
      static-network:
        ipv4_address: 173.20.128.56
  # adapter_2:
  #   build:
  #     context: ../
  #     dockerfile: ./p2p-bridge/Dockerfile
  #   depends_on:
  #     - ganache_net1
  #     - ganache_net2
  #   env_file:
  #     - ../eth-contracts/truffle/env_connect_to_network_1.env
  #     - ../eth-contracts/truffle/env_connect_to_network_2.env
  #   networks:
  #     static-network:
  #       ipv4_address: 173.20.128.58
  ganache_net1:
    build:
      context: ../
      dockerfile: ./eth-contracts/truffle/docker/network1/ganache/Dockerfile
    networks:
      static-network:
        ipv4_address: 173.20.128.11
    ports:
     - "7545:7545"

  ganache_net2:
    build:
      context: ../
      dockerfile: ./eth-contracts/truffle/docker/network2/ganache/Dockerfile
    networks:
      static-network:
        ipv4_address: 173.20.128.12
    ports:
     - "8545:8545"

networks:
  static-network:
    name: dev_net
    ipam:
      config:
        - subnet: 173.20.0.0/16
