version: '3.6'

services:

  adapter_1:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - ganache_net1
      - ganache_net2
    env_file:
      - ./env_p2p_bridge.env
    networks:
      static-network:
        ipv4_address: 172.20.128.55
    ports:
      - "8081:8081" # for debug


  adapter_2:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - ganache_net1
      - ganache_net2
    env_file:
      - ./env_p2p_bridge_2.env
    networks:
      static-network:
        ipv4_address: 172.20.128.58

  ganache_net1:
    build: ./docker/network1/ganache
    networks:
      static-network:
        ipv4_address: 172.20.128.11
    ports:
     - "7545:7545"

  ganache_net2:
    build: ./docker/network2/ganache
    networks:
      static-network:
        ipv4_address: 172.20.128.12
    ports:
     - "8545:8545"

networks:
  static-network:
    name: dev_net
    ipam:
      config:
        - subnet: 172.20.0.0/16


