version: '3.6'

services:

  bootstrap_node:
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - ./env_p2p_.env
    networks:
      static-network:
        ipv4_address: 152.20.128.55
    ports:
      - "8081:8081" # for debug


  node:
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - ./env_p2p__2.env
    networks:
      static-network:
        ipv4_address: 152.20.128.58




networks:
  static-network:
    name: bridge_p2p
