# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.16.0
    steps:
      - setup_remote_docker:
          version: 19.03.13
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt update
            sudo apt install docker.io
            sudo apt install docker-compose
            curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
            sudo apt install nodejs
            git submodule sync && git submodule update --init
            git submodule foreach -q --recursive 'git checkout $(git config -f $toplevel/.gitmodules submodule.$name.branch || echo main)'
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "./external/eth-contracts/truffle/package-lock.json" }}
            - v1-dependencies-
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
            # fallback to using the latest cache if no exact match is found
            - go-mod-v4-
      - run:
          name: Build
          command: |
            make -C external/eth-contracts
            make
            curl -sf https://gobinaries.com/tj/node-prune | sh
            ./bin/node-prune
            # cd scripts
            # ./deploy.sh
      - save_cache:
          key: v1-dependencies-{{ checksum "./external/eth-contracts/truffle/package-lock.json" }}
          paths:
            - " /node/pkg/modules"
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run tests
          command: |
            mkdir -p /tmp/test-reports
            # make -C external/eth-contracts local-test
            gotestsum --junitfile /tmp/test-reports/unit-tests.xml
      - store_test_results:
          path: /tmp/test-reports
